# Generated by Django 6.0.2 on 2026-02-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightissue',
            name='price_offered',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per share offered in rights issue', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rightissue',
            name='ratio',
            field=models.CharField(blank=True, help_text='Example: 1:2, 3:5 etc.', max_length=15, null=True),
        ),
    ]
