# Generated by Django 6.0.2 on 2026-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_rightissue_price_offered_rightissue_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightissue',
            name='on_appl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rightissue',
            name='on_call',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
